# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'RCTNative' do

  pod 'React', :path => './node_modules/react-native', :subspecs => [
	'Core',
	'RCTImage',
	'RCTNetwork',
	'RCTText',
	'RCTWebSocket',
]

end
