# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'RCTNative' do
  pod 'SDWebImage',     '~> 3.7.6'
  pod 'SDWebImage/WebP'
  pod 'React', :path => './node_modules/react-native', :subspecs => [
	'Core',
	'RCTImage',
	'RCTNetwork',
	'RCTText',
	'RCTWebSocket',
]

end
